### ISSUE TITLE
Make players join automatically

### ISSUE THREAD

**Issue by aymanelya** [pedrofracassi/amongcord#11]
Add players that are in a voice channel automatically instead of telling them to join manually

**Comment by pedrofracassi** [comment]
We'd need a way to detect their colors, though. Maybe if we add them to random colors?

**Comment by beingcarrot** [comment]
Yes, but we can do it like by using OCR and whenever the kill screen appears then parse it to the bot as the player is dead?

**Comment by beingcarrot** [comment]
But for that, we need to have the game run on every players' PC  <that's not my case though half of my friends play on the phone> XD

**Comment by pedrofracassi** [comment]
Soup's bot does that already: https://github.com/denverquane/amongusdiscord

Amongcord's objective is to require no local installation, but make it optional. I do plan to write some sort of capture tool for Windows/Android in the future, though.

**Comment by aymanelya** [comment]
> We'd need a way to detect their colors, though. Maybe if we add them to random colors?

exactly as only the names that matter during the game not the colors, everyone keeps changing colors anyways

**Comment by pedrofracassi** [comment]
I'll see what I can do.

**Comment by pedrofracassi** [comment]
Would `,joinall` be cool?

**Comment by aymanelya** [comment]
Yeah that would be great.

**Comment by pedrofracassi** [comment]
![image](https://user-images.githubusercontent.com/25179120/93689319-d77b0b80-faa3-11ea-9852-3d04655fa0a9.png)

oh hi there

**Comment by pedrofracassi** [comment]
No, don't close it yet! I'm not done :p
