### ISSUE TITLE
Add a statistics command

### ISSUE THREAD

**Issue by blazsmaster** [pedrofracassi/amongcord#17]
Create a ",stats" command like the image![PSX_20200920_004914.jpg](https://user-images.githubusercontent.com/64538277/93690656-49bb1280-fadb-11ea-9bc0-ac2e3e8653e6.jpg)

**Comment by pedrofracassi** [comment]
`,help` already shows the amount of servers the bot is in. Would there be some use case for the member count?

**Comment by blazsmaster** [comment]
> `,help` already shows the amount of servers the bot is in. Would there be some use case for the member count?

-servers
-members
-uptime

**Comment by iiftekhar** [comment]
I don't think there is any use case for this. (for playing among us) And I think there are many other bots for this. So if anyone really need this, he can add those bots in his server

**Comment by pedrofracassi** [comment]
I think this is out of the bot's scope. I have other tools for monitoring uptime, and member count doesn't matter too much to me.
