### ISSUE TITLE
Not issue just request some feature

### ISSUE THREAD

**Issue by Yourikura** [pedrofracassi/amongcord#6]
Please add feature on players command to see the color too, maybe use database?

**Comment by Yourikura** [comment]
please how to make base url?

**Comment by pedrofracassi** [comment]
The base URL is the address to the [Amongcord Sync](https://github.com/pedrofracassi/amongcord-sync) website http://sync.amongcord.xyz/. I'll add some sort of fallback so the bot doesn't break when it's missing.

**Comment by pedrofracassi** [comment]
Regarding the player command, it already shows color, but you need the emojis to be set up as described in the README. 

![image](https://user-images.githubusercontent.com/25179120/93375509-a34ae500-f82e-11ea-9300-91225956b1cc.png)
