### ISSUE TITLE
Using deafen so ghosts can talk during round.

### ISSUE THREAD

**Issue by dustinhudson** [pedrofracassi/amongcord#8]
Following up from Reddit.

My suggestion is using deafen instead of mute during tasks to allow ghosts to communicate.

You mentioned that one of your concerns is that you would require more API calls if you used deafen instead of muting, but in the worst case isn't it just 10 calls? Meeting called, x dead: 10-x API calls to undeafen, x calls to mute. Ten total API calls in any given meeting. I am not very familiar with the discord API rate limits, so I admit there may be issues I am not aware of.

The benefit of the way it is currently structured is that each time a player is killed, you have less calls overall. Although, in the worst case you would still have 10 API calls, i.e. discussion called, 0 dead, 10 setMute(false) calls.

One alternative is that you just deafen alive players during tasks and don't worry about muting dead players during meetings. In that case you have the same number of calls. That does require people to self police during discussions, so probably not the best solution.

**Comment by pedrofracassi** [comment]
> You mentioned that one of your concerns is that you would require more API calls if you used deafen instead of muting, but in the worst case isn't it just 10 calls? Meeting called, x dead: 10-x API calls to undeafen, x calls to mute. Ten total API calls in any given meeting. I am not very familiar with the discord API rate limits, so I admit there may be issues I am not aware of.

Exactly. Discord's API ratelimits the mute/deafen endpoint to 5 calls/5 seconds, so I'd have to wait up to 20 seconds to unmute/mute everyone, which is not really cool

**Comment by dustinhudson** [comment]
Why 20 seconds though? There are only 10 players and each should only have 1 call each during game stage transition, right? So at worst it should be 10 seconds, but in that case you can prioritize alive players over dead ones.

**Comment by pedrofracassi** [comment]
I have to mute the dead and undeafen the living, but I need to prioritize muting the dead, otherwise those who are alive will be able to hear them for a short period of time.

You're right about the seconds, though. 10 at worst, I think. There's _one_ small problem though: The bot is now in a 1000 servers without deafen permissions, so everyone will need to give it deafen permissions.

**Comment by dustinhudson** [comment]
True, it would probably be better to prioritize muting dead players. That second problem is definitely a bigger issue. It would not be great to have those 1000 servers update the bot for permissions. I guess I'll have to wait till you get around to the sync server address change you had mentioned to get my version working. That or maybe I can hack a much less pretty version of it together myself. :)

**Comment by pedrofracassi** [comment]
@dustinhudson sync source code is available over at https://github.com/pedrofracassi/amongcord-sync, it's a react app and should be pretty easy to set up. Just set `REACT_APP_SYNC_SERVER_ADDRESS` to whatever path your server can be found in

**Comment by bederman** [comment]
This should be an option, my friends and I prefer to have a music bot playing music during tasks phase while everyone is muted, so we don't want the deafening. Dead people can just chat in-game.
