### ISSUE TITLE
Manage Permissions for moderative commands (Kick, Sync, Newgame)

### ISSUE THREAD

**Issue by ThatOneDan** [pedrofracassi/amongcord#9]
Well I want to be able to split into different VCs and have a host per VC do the button pressing on the phone/site/kicking so no one else needs to do so or can mess with it and troll due to the fact that currently I cannot tell who is using the Sync functionality.

**Comment by pedrofracassi** [comment]
I'm going to close this favor of #10, which should get your case covered. Let's continue the discussion over there!
